# Generated by Django 5.1.6 on 2025-03-30 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hospitals',
            new_name='Hospital',
        ),
    ]
