# Generated by Django 5.1.6 on 2025-04-01 05:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalsApp', '0005_hospital_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=50)),
                ('receiver', models.CharField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('subject', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=2000)),
            ],
        ),
    ]
