# Generated by Django 5.1.6 on 2025-03-30 03:42

import HospitalsApp.validate
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitals',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, validators=[HospitalsApp.validate.validate_name])),
                ('zip_code', models.CharField(max_length=10, validators=[HospitalsApp.validate.validate_zip_code])),
                ('phone', models.CharField(max_length=16, validators=[HospitalsApp.validate.validate_phone])),
                ('type', models.CharField(max_length=10, validators=[HospitalsApp.validate.validate_type])),
                ('email', models.CharField(max_length=50, validators=[django.core.validators.EmailValidator()])),
            ],
        ),
    ]
