# Generated by Django 5.1.6 on 2025-03-30 19:57

import HospitalsApp.validate
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalsApp', '0002_rename_hospitals_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='phone',
            field=models.CharField(max_length=14, validators=[HospitalsApp.validate.validate_phone]),
        ),
    ]
