# Generated by Django 5.1.6 on 2025-03-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalsApp', '0004_alter_hospital_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
