# Generated by Django 5.1.6 on 2025-04-03 22:28

import HospitalsApp.validate
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalsApp', '0006_myemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, validators=[HospitalsApp.validate.validate_name]),
        ),
    ]
