# Generated by Django 5.1.6 on 2025-04-04 07:15

import HospitalsApp.validate
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalsApp', '0007_alter_hospital_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='type',
            field=models.CharField(max_length=9, validators=[HospitalsApp.validate.validate_type]),
        ),
    ]
